### ISSUE TITLE
How  to upsample the Dis-Map into the image size?

### ISSUE THREAD

**Issue by nchuCV** [ZhengyuZhao/Adaptive-Discriminative-Region-Discovery#1]
Hello，I am reading this paper recently.  I don't know how to upsample the Dis-Map into the image size.

**Comment by ZhengyuZhao** [comment]
In this paper, I used the 'imresize' function from the package scipy.misc. So basically, 
the code could be ''from scipy.misc import imresize as imresize'' and then you can use imresize function to map the Dis-Map into the original size of that image.

**Comment by ZhengyuZhao** [comment]
> Hello，I am reading this paper recently. I don't know how to upsample the Dis-Map into the image size.

In this paper, I used the 'imresize' function from the package scipy.misc. So basically,
the code could be ''from scipy.misc import imresize as imresize'' and then you can use imresize function to map the Dis-Map into the original size of that image.
