### ISSUE TITLE
how to train this model??

### ISSUE THREAD

**Issue by ziziyaziziya** [ZhengyuZhao/Adaptive-Discriminative-Region-Discovery#14]
Hello I want to know how to train this network with my own data set

**Comment by ZhengyuZhao** [comment]
> Hello I want to know how to train this network with my own data set




> Hello I want to know how to train this network with my own data set

Sorry for the late reply...There is no training process in our proposed method. See another previous issue for more details about our process in https://github.com/ZhengyuZhao/Adi-Red-Scene/issues/5.
