### ISSUE TITLE
ModuleNotFoundError: No module named 'wideresnet'

### ISSUE THREAD

**Issue by nchuCV** [ZhengyuZhao/Adaptive-Discriminative-Region-Discovery#2]
当加载 whole_wideresnet18_places365_python36.pth.tar model的时候，总是出现 
ModuleNotFoundError: No module named 'wideresnet' 错误，不知道怎么回事

**Comment by ZhengyuZhao** [comment]
> 当加载 whole_wideresnet18_places365_python36.pth.tar model的时候，总是出现
> ModuleNotFoundError: No module named 'wideresnet' 错误，不知道怎么回事

You can open this address http://places2.csail.mit.edu/models_places365/whole_wideresnet18_places365_python36.pth.tar
to download this model directly. Then you will be able to load this model from your local disk. :-)

**Comment by nchuCV** [comment]
> > 当加载 whole_wideresnet18_places365_python36.pth.tar model的时候，总是出现
> > ModuleNotFoundError: No module named 'wideresnet' 错误，不知道怎么回事
> 
> You can open this address http://places2.csail.mit.edu/models_places365/whole_wideresnet18_places365_python36.pth.tar
> to download this model directly. Then you will be able to load this model from your local disk. :-)

In this way, I will still have this problem.

**Comment by rishav130** [comment]
the above link is damaged

**Comment by ZhengyuZhao** [comment]
> the above link is damaged

Hi, I can still open the above link, could you please try again?
