### ISSUE TITLE
How to understand the code "top=np.int32(a*ratio)-112"?

### ISSUE THREAD

**Issue by joniea** [ZhengyuZhao/Adaptive-Discriminative-Region-Discovery#7]
Hi,I am reading this paper recently,in your paper ,There is such a sentence in your paper that we use two different patch sizes (1/4 and 1/16 of the image size).but  the implementation part of the code  is described like this top=np.int32(a*ratio)-112 left=np.int32(b*ratio)-112 left=np.maximum(left,0) right=left+224 ,...can you offer some suggestions? thank you !

**Comment by ZhengyuZhao** [comment]
> Hi,I am reading this paper recently,in your paper ,There is such a sentence in your paper that we use two different patch sizes (1/4 and 1/16 of the image size).but the implementation part of the code is described like this top=np.int32(a_ratio)-112 left=np.int32(b_ratio)-112 left=np.maximum(left,0) right=left+224 ,...can you offer some suggestions? thank you !

Thanks for your interest in our work and sorry for the late reply...
Take the demo.py as an example, the code between line 141-165 is for selecting the discriminative patches. In the implementation, each original image sized with 224x224 is upsampled to either 448x448 or 896x896, which is denoted as scale_image_size in the code. Then, discriminative patches with a fixed size of 224x224 will be cropped. So the ratio of any patch to images sized with 448x448 is 1/4, and 1/16 for those with 896x896.
The top, down, left, and right together determine the coordinate position of a selected patch in the upsampled image.

**Comment by keaixiaovv** [comment]
Hello my friend！I am reproducing your entire experiment, but there are some problems when running your code, I cannot open the follow URL 
  os.system ('wget https://raw.githubusercontent.com/csailvision/places365/master/wideresnet.py'+' -P ./examples') 
to download the wideresnet model, Could you please upload wideresnet.py to this folder？Thank you!
