### ISSUE TITLE
Cannot import wideresnet

### ISSUE THREAD

**Issue by keaixiaovv** [ZhengyuZhao/Adaptive-Discriminative-Region-Discovery#8]
Hello my friend！I am reproducing your entire experiment, but there are some problems when running your code, I cannot open the follow URL
os.system ('wget https://raw.githubusercontent.com/csailvision/places365/master/wideresnet.py'+' -P ./examples')
to download the wideresnet model, Could you please upload wideresnet.py to this folder？Thank you!

**Comment by ZhengyuZhao** [comment]
> Hello my friend！I am reproducing your entire experiment, but there are some problems when running your code, I cannot open the follow URL
> os.system ('wget https://raw.githubusercontent.com/csailvision/places365/master/wideresnet.py'+' -P ./examples')
> to download the wideresnet model, Could you please upload wideresnet.py to this folder？Thank you!

Thanks for your interest in our work! You can get 'wideresnet.py' by directly accessing the website: https://raw.githubusercontent.com/csailvision/places365/master/wideresnet.py

**Comment by keaixiaovv** [comment]
I'm sorry to bother you again. I can not open this page because the display address is invalid.
In addition, I have another question to consult. If I want to use DisNet to train other datasets and modify the weights in them, could I get the .py file of your model and pre-train it in other datasets? Thank you!

**Comment by ZhengyuZhao** [comment]
> I'm sorry to bother you again. I can not open this page because the display address is invalid.
> In addition, I have another question to consult. If I want to use DisNet to train other datasets and modify the weights in them, could I get the .py file of your model and pre-train it in other datasets? Thank you!

This is weird cause I can still open the website...Please check the address again (The default address in your initial question is not correctly hyperlinked...)

Regarding another question, there is actually no training in our DisNet. Instead, it is just a ResNet pre-trained on Places 365, which is used to automatically localize the discriminative regions in the scene images (see ref. [33] in our paper for this idea). So, you can definitely train another ResNet model on other datasets, and then use it to localize discriminative regions in your images.
